apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vector-store-manager-server.fullname" . }}
  labels:
    {{- include "vector-store-manager-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vector-store-manager-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vector-store-manager-server.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ sha256sum (toJson .Values) }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "vector-store-manager-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: vector-store-manager-server
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ default .Chart.Version .Values.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - run
        - --config
        - /etc/config/config.yaml
        ports:
        - name: http
          containerPort: {{ .Values.httpPort }}
          protocol: TCP
        - name: grpc
          containerPort: {{ .Values.grpcPort }}
          protocol: TCP
        - name: internal-grpc
          containerPort: {{ .Values.internalGrpcPort }}
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: tmp
          mountPath: /tmp
        {{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.databaseSecret.name }}
              key: {{ .Values.global.databaseSecret.key }}
        - name: VECTOR_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.vectorDatabaseSecret.name }}
              key: {{ .Values.vectorDatabaseSecret.key }}
        {{- with .Values.global.awsSecret }}
        {{- if .name }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: {{ .accessKeyIdKey }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: {{ .secretAccessKeyKey }}
        {{- end }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "vector-store-manager-server.fullname" . }}
      - name: tmp
        emptyDir:
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
